# Generated by Django 3.1.3 on 2021-04-05 05:23

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_data',
            field=models.FileField(upload_to=common.models.get_file_path),
        ),
    ]
