# Generated by Django 3.1.3 on 2021-04-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210428_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
