# Generated by Django 3.1.3 on 2021-04-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_menu_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='argument',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
