# Generated by Django 3.1.3 on 2021-04-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20210429_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='argument',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
