# Generated by Django 3.1.3 on 2021-03-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_reply_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
