# Generated by Django 3.1.3 on 2021-03-13 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('board', '0006_auto_20210312_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu_board', to='common.menu'),
            preserve_default=False,
        ),
    ]
