# Generated by Django 3.1.3 on 2021-03-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_board_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='hit_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
