# Generated by Django 3.1.3 on 2021-03-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_board_hit_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='hit_count',
            field=models.IntegerField(default=0),
        ),
    ]
