# Generated by Django 3.1.3 on 2021-03-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20210316_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
