# Generated by Django 3.1.3 on 2021-03-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_board_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='file',
        ),
    ]
